### ISSUE TITLE
Battery state and IsCharging incorrectly show charging when phone is not charging.

### ISSUE THREAD

**Issue by TriploidTree** [home-assistant/android#2473]
**Home Assistant Android version:**
2022.3.0-full

**Android version:**
12

**Phone model:**
One Plus 9 Pro, LE2123

**Home Assistant version:**
2022.4.6

**Last working Home Assistant release (if known):**
Not seen working since the app was installed ~1w ago

**Description of problem:**
Battery state and IsCharging states are not correct. 

When the phone is unplugged they show as "charging" and "Plugged in" respectively. Charger type is correctly "none"
![image](https://user-images.githubusercontent.com/4170521/164999792-b770df8b-1f1b-4eba-bc38-5ab6c81a4a1c.png)

When plugged in, Battery state and IsCharging are correct (stopped clock etc), and Charger Type is "ac"

![image](https://user-images.githubusercontent.com/4170521/164999837-29c932fa-fe0c-4a3c-853d-f2d456d05615.png)

Expected behaviour:
 When the phone is not charging, Battery state does not show charging, IsCharging does not show "plugged in"

**Traceback (if applicable, to get the logs you may refer to: https://companion.home-assistant.io/docs/troubleshooting/faqs/#android-crash-logs):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
are there any errors in the logs? Check Configuration > Companion App > Logs to see if there is a failure when you unplug the device.

**Comment by TriploidTree** [comment]
So in the logs, I plugged and unplugged just there and I got:

`04-25 00:00:18.180 31517 31517 W Choreographer: Frame time is 0.01897 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.

04-25 00:00:28.866 31517 31517 D SensorReceiver: Received intent: android.intent.action.ACTION_POWER_CONNECTED

04-25 00:00:28.957 31517  9018 D UrlRepository: localUrl is: false and usesInternalSsid is: false

04-25 00:00:34.097 31517  9018 D SensorReceiver: Nothing to update

04-25 00:00:44.695 31517 31517 D SensorReceiver: Received intent: android.intent.action.ACTION_POWER_DISCONNECTED

04-25 00:00:44.771 31517  9018 D UrlRepository: localUrl is: false and usesInternalSsid is: false

04-25 00:00:46.555 31517  9018 D LogcatReader: Read logcat for pid 31517`

**Comment by dshokouhi** [comment]
ok looks like the intents are being received but for some reason the sensor is not being updated, please follow the start fresh steps precisely and it should solve the issue.

https://companion.home-assistant.io/docs/troubleshooting/faqs/#starting-fresh-with-the-android-app

**Comment by TriploidTree** [comment]
Tried the starting fresh, same scenario. Charger type updates correctly to none/ac but Battery State and IsCharging still show charging/plugged in regardless of state

**Comment by dshokouhi** [comment]
and there were no errors observed after logging in? Can you double check those sensors are still enabled? Is the device running stock ROM? The sensors should be enabled by default and they are very basic and work on a large set of devices one plus included so something else must be going on here. Were there any HA side errors?

**Comment by TriploidTree** [comment]
Sensors are all still enabled, turning them on and off doesn't resolve the state.
Stock ROM, too lazy to try anything else...
Only errror on the HA side was me using the wrong password to authenticate on the app. 
Nothing obvious on the app logs. No errors on logging in (apart from using the wrong password)

**Comment by dshokouhi** [comment]
I am not really sure what could be causing that issue, the APIs used are very standard here and I cannot reproduce on my Pixel.  Its almost as if the Android API is returning the data that does not look correct and if that is the case there is nothing we can do here. The sensors in question are not using the default values, they are using actual reported values.  Do you have another device to test on to rule out a device issue?
