### ISSUE TITLE
Device control does not work with version 5.6.3

### ISSUE THREAD

**Issue by meldarionqeusse** [home-assistant/android#5435]
**Home Assistant Android app version(s):**

**Android version(s):** 5.6.3

**Device model(s):** moto g73

**Home Assistant version:** 2025.6.1

**Last working Home Assistant release (if known):** 2025.5.3

**Description of problem, include YAML if issue is related to notifications:** device control stay loading see

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by dshokouhi** [comment]
Please fill out hte issue template completely including the missing logs, linking to another very old issue is not enough information.

**Comment by meldarionqeusse** [comment]
Sorry i did not know how to get to them and did jot have too much time to look further into it. I want to report that the issue is also occuring with 5.6.6.

Logs from companion app below: 

```
--------- beginning of system
07-05 19:15:54.216 14011 14011 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:15:54.216 14011 14011 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:15:54.216 14011 14011 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:15:54.216 14011 14011 D ViewRootImpl:   bhv=DEFAULT
07-05 19:15:54.216 14011 14011 D ViewRootImpl:   fitSides=} by setView
07-05 19:15:54.691 14011 14011 D ViewRootImpl: update {(0,0)(wrapxwrap) gr=CENTER sim={adjust=pan forwardNavigation} ty=APPLICATION fmt=TRANSLUCENT wanim=0x10302ff
07-05 19:15:54.691 14011 14011 D ViewRootImpl:   fl=DIM_BEHIND ALT_FOCUSABLE_IM SPLIT_TOUCH HARDWARE_ACCELERATED
07-05 19:15:54.691 14011 14011 D ViewRootImpl:   bhv=DEFAULT
07-05 19:15:54.691 14011 14011 D ViewRootImpl:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setView
07-05 19:15:54.704 14011 14011 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:15:54.704 14011 14011 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:15:54.704 14011 14011 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:15:54.704 14011 14011 D ViewRootImpl:   bhv=DEFAULT
07-05 19:15:54.704 14011 14011 D ViewRootImpl:   fitSides=} by setView
--------- beginning of main
07-05 19:17:03.995 14011 14011 D LocationSensorManager: Received location update.
07-05 19:17:04.005 14011 14011 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
07-05 19:17:04.006 14011 14067 D LocationSensorManager: Last Location: 
07-05 19:17:04.006 14011 14067 D LocationSensorManager: Coords:(35.8275162, 14.4779711)
07-05 19:17:04.006 14011 14067 D LocationSensorManager: Accuracy: 200.0
07-05 19:17:04.006 14011 14067 D LocationSensorManager: Bearing: 0.0
07-05 19:17:04.008 14011 14067 D LocationSensorManager: Begin evaluating if location update should be skipped
07-05 19:17:04.008 14011 14067 D LocationSensorManager: Received location that is 55 milliseconds old, 1751735823952 compared to 1751735824007 with source fused
07-05 19:17:04.008 14011 14067 D LocationSensorManager: Duplicate location received, not sending to HA
07-05 19:17:50.917 14011 14011 D WebViewActivity$onCreate: Matter/Thread step changed to NOT_STARTED
07-05 19:17:50.919 14011 14011 D ServerConnectionInfo: Using external URL
07-05 19:17:50.919 14011 14011 D ServerConnectionInfo: Using external URL
07-05 19:17:50.919 14011 14011 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1751735870919)
07-05 19:17:50.929 14011 14011 D VRI[WebViewActivity]: update {(0,0)(fillxfill) ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:17:50.929 14011 14011 D VRI[WebViewActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:17:50.929 14011 14011 D VRI[WebViewActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:17:50.929 14011 14011 D VRI[WebViewActivity]:   bhv=DEFAULT
07-05 19:17:50.929 14011 14011 D VRI[WebViewActivity]:   fitSides=} by setLayoutParams
07-05 19:17:50.931 14011 14045 D WM-Processor: Processor cancelling 94d181ff-6cb2-47e5-a6d5-b0a8a4381420
07-05 19:17:50.931 14011 14045 D WM-Processor: WorkerWrapper could not be found for 94d181ff-6cb2-47e5-a6d5-b0a8a4381420
07-05 19:17:50.935 14011 14045 D WM-GreedyScheduler: Cancelling work ID 94d181ff-6cb2-47e5-a6d5-b0a8a4381420
07-05 19:17:50.942 14011 14045 D WM-SystemJobScheduler: Scheduling work ID bf1360c5-2a37-4d10-8175-db4ea9e4b9cbJob ID 7361
07-05 19:17:50.950 14011 14045 D WM-GreedyScheduler: Starting tracking for bf1360c5-2a37-4d10-8175-db4ea9e4b9cb
07-05 19:17:50.952 14011 14045 D WM-Processor: Processor cancelling 84621ae0-2414-46af-a03c-fca97ba18342
07-05 19:17:50.952 14011 14045 D WM-Processor: WorkerWrapper could not be found for 84621ae0-2414-46af-a03c-fca97ba18342
07-05 19:17:50.955 14011 14045 D WM-GreedyScheduler: Cancelling work ID 84621ae0-2414-46af-a03c-fca97ba18342
07-05 19:17:50.968 14011 14045 D WM-SystemJobScheduler: Scheduling work ID 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6Job ID 7362
07-05 19:17:50.976 14011 14045 D WM-GreedyScheduler: Starting work for 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6
07-05 19:17:50.976 14011 14045 D WM-GreedyScheduler: Starting tracking for bf1360c5-2a37-4d10-8175-db4ea9e4b9cb
07-05 19:17:50.977 14011 14045 D WM-Processor: Processor: processing WorkGenerationalId(workSpecId=968579ee-b3b3-4ab6-bcf6-a03dce90c4a6, generation=0)
07-05 19:17:50.980 14011 14045 D WM-ConstraintTracker: NetworkStateTracker24: initial state = NetworkState(isConnected=true, isValidated=true, isMetered=false, isNotRoaming=true)
07-05 19:17:50.983 14011 14045 D WM-NetworkStateTracker: Registering network callback
07-05 19:17:50.987 14011 14078 D WM-NetworkStateTracker: Network capabilities changed: [ Transports: WIFI Capabilities: NOT_METERED&INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&VALIDATED&NOT_ROAMING&FOREGROUND&NOT_CONGESTED&NOT_SUSPENDED&NOT_VCN_MANAGED LinkUpBandwidth>=12000Kbps LinkDnBandwidth>=60000Kbps TransportInfo: <SSID: <unknown ssid>, BSSID: 02:00:00:00:00:00, MAC: 02:00:00:00:00:00, IP: /192.168.0.141, Security type: 2, Supplicant state: COMPLETED, Wi-Fi standard: 11ac, RSSI: -60, Link speed: 292Mbps, Tx Link speed: 292Mbps, Max Supported Tx Link speed: 433Mbps, Rx Link speed: 6Mbps, Max Supported Rx Link speed: 433Mbps, Frequency: 5180MHz, Net ID: -1, Metered hint: false, score: 60, isUsable: true, CarrierMerged: false, SubscriptionId: -1, IsPrimary: -1, Trusted: true, Restricted: false, Ephemeral: false, OEM paid: false, OEM private: false, OSU AP: false, FQDN: <none>, Provider friendly name: <none>, Requesting package name: <none><none>MLO Information: , Is TID-To-Link negotiation supported by the AP: false, AP MLD Address: <none>, AP MLO Link Id: <none>, AP MLO Affiliated links: <none>, Vendor Data: <none>> SignalStrength: -60 UnderlyingNetworks: Null]
07-05 19:17:50.988 14011 14055 D WM-GreedyScheduler: Constraints met: Scheduling work ID WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0)
07-05 19:17:50.989 14011 14055 D WM-Processor: Processor: processing WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0)
07-05 19:17:51.003 14011 14011 D VRI[WebViewActivity]: update {(0,0)(fillxfill) sim={adjust=pan forwardNavigation} ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:17:51.003 14011 14011 D VRI[WebViewActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:17:51.003 14011 14011 D VRI[WebViewActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND USE_BLAST APPEARANCE_CONTROLLED FIT_INSETS_CONTROLLED
07-05 19:17:51.003 14011 14011 D VRI[WebViewActivity]:   bhv=DEFAULT
07-05 19:17:51.003 14011 14011 D VRI[WebViewActivity]:   fitSides=} by setLayoutParams
07-05 19:17:51.009 14011 14011 D BufferQueueConsumer: [](id:36bb00000003,api:0,p:-1,c:14011) connect: controlledByApp=false
07-05 19:17:51.011 14011 14222 E OpenGLRenderer: Unable to match the desired swap behavior.
07-05 19:17:51.030 14011 14222 D BLASTBufferQueue: [VRI[WebViewActivity]#3](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=738765616751495(auto) mPendingTransactions.size=0 graphicBufferId=60176786784288 transform=0
07-05 19:17:51.036 14011 14011 D WM-WorkerWrapper: Starting work for io.homeassistant.companion.android.websocket.WebsocketManager
07-05 19:17:51.036 14011 14011 D WM-WorkerWrapper: Starting work for io.homeassistant.companion.android.sensors.SensorWorker
07-05 19:17:51.038 14011 14011 D WM-SystemJobService: onStartJob for WorkGenerationalId(workSpecId=968579ee-b3b3-4ab6-bcf6-a03dce90c4a6, generation=0)
07-05 19:17:51.038 14011 14055 I WM-Processor: Moving WorkSpec (bf1360c5-2a37-4d10-8175-db4ea9e4b9cb) to the foreground
07-05 19:17:51.039 14011 14011 D WM-SystemJobService: onStartJob for WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0)
07-05 19:17:51.046 14011 14011 D ServerConnectionInfo: Using external URL
07-05 19:17:51.047 14011 14011 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1751735871047)
07-05 19:17:51.053 14011 14011 D ServerConnectionInfo: Using external URL
07-05 19:17:51.053 14011 14011 D ServerConnectionInfo: Using external URL
07-05 19:17:51.053 14011 14011 I WM-SystemFgDispatcher: Started foreground service Intent { act=ACTION_START_FOREGROUND cmp=io.homeassistant.companion.android/androidx.work.impl.foreground.SystemForegroundService (has extras) }
07-05 19:17:51.053 14011 14011 D WM-SystemFgDispatcher: Notifying with (id:42, workSpecId: bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, notificationType :1)
07-05 19:17:51.055 14011 14055 D WM-Processor: Work WorkGenerationalId(workSpecId=968579ee-b3b3-4ab6-bcf6-a03dce90c4a6, generation=0) is already enqueued for processing
07-05 19:17:51.056 14011 14055 D WM-Processor: Work WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0) is already enqueued for processing
07-05 19:17:51.058 14011 14058 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=968579ee-b3b3-4ab6-bcf6-a03dce90c4a6, tags={ io.homeassistant.companion.android.websocket.WebsocketManager } ]
07-05 19:17:51.062 14011 14011 D WM-SystemFgDispatcher: Notifying with (id:42, workSpecId: bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, notificationType :1)
07-05 19:17:51.063 14011 14210 D SensorWorkerBase$doWork: Updating all Sensors in foreground.
07-05 19:17:51.066 14011 14210 D ServerConnectionInfo: Using external URL
07-05 19:17:51.067 14011 14011 D WM-Processor: Processor 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6 executed; reschedule = false
07-05 19:17:51.067 14011 14011 D WM-SystemJobService: 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6 executed on JobScheduler
07-05 19:17:51.071 14011 14058 D WM-GreedyScheduler: Cancelling work ID 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6
07-05 19:17:51.086 14011 14058 D WM-SystemJobScheduler: Scheduling work ID 968579ee-b3b3-4ab6-bcf6-a03dce90c4a6Job ID 7362
07-05 19:17:51.167 14011 14017 W mpanion.android: Cleared Reference was only reachable from finalizer (only reported once)
07-05 19:17:51.212 14011 14017 I mpanion.android: Background concurrent mark compact GC freed 33MB AllocSpace bytes, 81(9328KB) LOS objects, 75% free, 8683KB/33MB, paused 2.947ms,6.681ms total 87.898ms
07-05 19:17:51.217 14011 14210 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
07-05 19:17:51.364 14011 14210 D LocationSensorManager: High accuracy mode disabled, because defined ([5C:46:B0:D1:D1:CE]) bluetooth device(s) not connected (Connected devices: [BluetoothDevice(address=00:1A:7D:DA:71:13, name=OPTIPLEX790, paired=true, connected=false), BluetoothDevice(address=E8:EE:CC:6B:3D:E9, name=soundcore A20i, paired=true, connected=false), BluetoothDevice(address=41:42:60:CC:34:96, name=PMK SPEAKER, paired=true, connected=false), BluetoothDevice(address=5C:46:B0:D1:D1:CE, name=LeapmotorT03, paired=true, connected=false), BluetoothDevice(address=E8:EE:CC:80:1A:A3, name=soundcore A20i, paired=true, connected=false), BluetoothDevice(address=00:02:3C:61:64:F3, name=Creative OUTLIER, paired=true, connected=false), BluetoothDevice(address=1C:17:22:F2:DE:3D, name=AE01, paired=true, connected=false), BluetoothDevice(address=32:00:24:50:00:01, name=BT BIAO-TA, paired=true, connected=false), BluetoothDevice(address=F0:99:19:28:3F:7D, name=vívoactive 3 Music, paired=true, connected=false), BluetoothDevice(address=88:88:00:00:4D:13, name=HX-A19731, paired=true, connected=false), BluetoothDevice(address=00:02:3C:05:93:C8, name=Sound Blaster FRee, paired=true, connected=false), BluetoothDevice(address=14:6C:27:1A:65:E6, name=soundcore V20i, paired=true, connected=false), BluetoothDevice(address=08:F0:B6:98:85:D0, name=EDIFIER D12, paired=true, connected=false), BluetoothDevice(address=1C:66:6D:41:65:71, name=Wireless Controller, paired=true, connected=false), BluetoothDevice(address=EC:85:D5:EB:99:C5, name=Keychron K3 Max, paired=true, connected=false)])
07-05 19:17:51.504 14011 14210 D SensorReceiverBase: Nothing to update for server 1 (https://home.thewolves.cyou/)
07-05 19:17:51.504 14011 14210 I SensorReceiverBase: Sensor updates and sync completed
07-05 19:17:51.507 14011 14058 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
07-05 19:17:51.513 14011 14011 D WM-Processor: Processor bf1360c5-2a37-4d10-8175-db4ea9e4b9cb executed; reschedule = false
07-05 19:17:51.514 14011 14011 D WM-GreedyScheduler: Stopping tracking for WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0)
07-05 19:17:51.514 14011 14011 D WM-SystemJobService: bf1360c5-2a37-4d10-8175-db4ea9e4b9cb executed on JobScheduler
07-05 19:17:51.514 14011 14011 D WM-SystemFgDispatcher: Removing Notification (id: 42, workSpecId: WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0), notificationType: 1
07-05 19:17:51.514 14011 14011 I WM-SystemFgDispatcher: Stopping foreground service
07-05 19:17:51.514 14011 14011 D WM-SystemFgService: Shutting down.
07-05 19:17:51.519 14011 14058 D WM-GreedyScheduler: Cancelling work ID bf1360c5-2a37-4d10-8175-db4ea9e4b9cb
07-05 19:17:51.523 14011 14011 D WM-SystemJobService: onStopJob for WorkGenerationalId(workSpecId=bf1360c5-2a37-4d10-8175-db4ea9e4b9cb, generation=0)
07-05 19:17:51.523 14011 14058 D WM-SystemJobScheduler: Scheduling work ID bf1360c5-2a37-4d10-8175-db4ea9e4b9cbJob ID 7363
07-05 19:17:51.535 14011 14058 D WM-NetworkStateTracker: Unregistering network callback
07-05 19:17:58.113 14011 14280 D WebViewActivity$webViewAddJavascriptInterface: External bus {"type":"config_screen/show","id":4}
07-05 19:17:58.131 14011 14011 D IntegrationRepositoryImpl: setAppActive(): false
07-05 19:17:58.132 14011 14011 D IntegrationRepositoryImpl: setAppActive(): false
07-05 19:17:58.141 14011 14011 D SensorReceiverBase: Received intent: io.homeassistant.companion.android.UPDATE_SENSORS
07-05 19:17:58.142 14011 14210 D ServerConnectionInfo: Using external URL
07-05 19:17:58.147 14011 15176 D libMEOW : meow new tls: 0xb40000726db47840
07-05 19:17:58.147 14011 15176 D libMEOW : applied 1 plugins for [io.homeassistant.companion.android]:
07-05 19:17:58.147 14011 15176 D libMEOW :   plugin 1: [libMEOW_gift.so]: 0xb400007384d32380
07-05 19:17:58.147 14011 15176 D libMEOW : rebuild call chain: 0xb40000726db56280
07-05 19:17:58.148 14011 15176 D libMEOW : meow delete tls: 0xb40000726db47840
07-05 19:17:58.184 14011 14210 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
07-05 19:17:58.263 14011 14011 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1751735878263)
07-05 19:17:58.267 14011 14011 D ViewRootImpl: update {(0,0)(fillxfill) sim={forwardNavigation} layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:17:58.267 14011 14011 D ViewRootImpl:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:17:58.267 14011 14011 D ViewRootImpl:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:17:58.267 14011 14011 D ViewRootImpl:   bhv=DEFAULT
07-05 19:17:58.267 14011 14011 D ViewRootImpl:   fitSides=} by setView
07-05 19:17:58.272 14011 14210 D LocationSensorManager: High accuracy mode disabled, because defined ([5C:46:B0:D1:D1:CE]) bluetooth device(s) not connected (Connected devices: [BluetoothDevice(address=00:1A:7D:DA:71:13, name=OPTIPLEX790, paired=true, connected=false), BluetoothDevice(address=E8:EE:CC:6B:3D:E9, name=soundcore A20i, paired=true, connected=false), BluetoothDevice(address=41:42:60:CC:34:96, name=PMK SPEAKER, paired=true, connected=false), BluetoothDevice(address=5C:46:B0:D1:D1:CE, name=LeapmotorT03, paired=true, connected=false), BluetoothDevice(address=E8:EE:CC:80:1A:A3, name=soundcore A20i, paired=true, connected=false), BluetoothDevice(address=00:02:3C:61:64:F3, name=Creative OUTLIER, paired=true, connected=false), BluetoothDevice(address=1C:17:22:F2:DE:3D, name=AE01, paired=true, connected=false), BluetoothDevice(address=32:00:24:50:00:01, name=BT BIAO-TA, paired=true, connected=false), BluetoothDevice(address=F0:99:19:28:3F:7D, name=vívoactive 3 Music, paired=true, connected=false), BluetoothDevice(address=88:88:00:00:4D:13, name=HX-A19731, paired=true, connected=false), BluetoothDevice(address=00:02:3C:05:93:C8, name=Sound Blaster FRee, paired=true, connected=false), BluetoothDevice(address=14:6C:27:1A:65:E6, name=soundcore V20i, paired=true, connected=false), BluetoothDevice(address=08:F0:B6:98:85:D0, name=EDIFIER D12, paired=true, connected=false), BluetoothDevice(address=1C:66:6D:41:65:71, name=Wireless Controller, paired=true, connected=false), BluetoothDevice(address=EC:85:D5:EB:99:C5, name=Keychron K3 Max, paired=true, connected=false)])
07-05 19:17:58.288 14011 14011 D BufferQueueConsumer: [](id:36bb00000004,api:0,p:-1,c:14011) connect: controlledByApp=false
07-05 19:17:58.290 14011 14222 E OpenGLRenderer: Unable to match the desired swap behavior.
07-05 19:17:58.346 14011 14210 D SensorReceiverBase: Nothing to update for server 1 (https://home.thewolves.cyou/)
07-05 19:17:58.346 14011 14210 I SensorReceiverBase: Sensor updates and sync completed
07-05 19:17:58.366 14011 14222 D BLASTBufferQueue: [VRI[SettingsActivity]#4](f:0,a:1) acquireNextBufferLocked size=1080x2400 mFrameNumber=1 applyTransaction=true mTimestamp=738772952298495(auto) mPendingTransactions.size=0 graphicBufferId=60176786784301 transform=0
07-05 19:17:58.369 14011 14210 D ServerConnectionInfo: Using external URL
07-05 19:17:58.371 14011 14011 D CompatibilityChangeReporter: Compat change id reported: 303742236; UID 10385; state: DISABLED
07-05 19:17:58.421 14011 14011 D SettingsWearDetection: API unavailable for discovering nodes (no Wear)
07-05 19:17:58.533 14011 14011 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: false, expireMillis: 0, currentMillis: 1751735878532)
07-05 19:17:58.534 14011 14011 D IntegrationRepositoryImpl: setAppActive(): true
07-05 19:17:58.926 14011 14222 D Surface : Surface::disconnect
07-05 19:17:58.930 14011 14011 D BLASTBufferQueue: [VRI[WebViewActivity]#3](f:0,a:2) destructor()
07-05 19:17:58.930 14011 14011 D BufferQueueConsumer: [VRI[WebViewActivity]#3(BLAST Consumer)3](id:36bb00000003,api:0,p:-1,c:14011) disconnect
07-05 19:17:58.937 14011 14011 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=androidx.activity.OnBackPressedDispatcher$Api34Impl$createOnBackAnimationCallback$1@827f9e9
07-05 19:18:03.972 14011 14011 D LocationSensorManager: Received location update.
07-05 19:18:03.973 14011 14011 D ForegroundServiceLauncher: Check if service HighAccuracyLocationService is running. Service running = false
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Last Location: 
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Coords:(35.8275162, 14.4779711)
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Accuracy: 200.0
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Bearing: 0.0
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Begin evaluating if location update should be skipped
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Received location that is 22 milliseconds old, 1751735883952 compared to 1751735883974 with source fused
07-05 19:18:03.974 14011 14210 D LocationSensorManager: Duplicate location received, not sending to HA
07-05 19:18:11.637 14011 14011 E mpanion.android: Invalid resource ID 0x00000000.
07-05 19:18:11.682 14011 14011 D ViewRootImpl: update {(0,0)(wrapxwrap) gr=CENTER sim={adjust=pan forwardNavigation} ty=APPLICATION fmt=TRANSLUCENT wanim=0x10302ff
07-05 19:18:11.682 14011 14011 D ViewRootImpl:   fl=DIM_BEHIND ALT_FOCUSABLE_IM SPLIT_TOUCH HARDWARE_ACCELERATED
07-05 19:18:11.682 14011 14011 D ViewRootImpl:   bhv=DEFAULT
07-05 19:18:11.682 14011 14011 D ViewRootImpl:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setView
07-05 19:18:11.709 14011 14011 D BufferQueueConsumer: [](id:36bb00000005,api:0,p:-1,c:14011) connect: controlledByApp=false
07-05 19:18:11.711 14011 14222 E OpenGLRenderer: Unable to match the desired swap behavior.
07-05 19:18:11.719 14011 14222 D BLASTBufferQueue: [VRI[SettingsActivity]#5](f:0,a:1) acquireNextBufferLocked size=1186x612 mFrameNumber=1 applyTransaction=true mTimestamp=738786305739804(auto) mPendingTransactions.size=0 graphicBufferId=60176786784309 transform=0
07-05 19:18:11.741 14011 14222 D Surface : Surface::disconnect
07-05 19:18:11.742 14011 14222 E OpenGLRenderer: Unable to match the desired swap behavior.
07-05 19:18:11.757 14011 14222 D BLASTBufferQueue: [VRI[SettingsActivity]#5](f:0,a:3) producer disconnected before acquireNextBufferLocked
07-05 19:18:12.897 14011 14011 W WindowOnBackDispatcher: sendCancelIfRunning: isInProgress=falsecallback=android.app.Dialog$$ExternalSyntheticLambda2@2e84b4f
07-05 19:18:12.902 14011 14222 D Surface : Surface::disconnect
07-05 19:18:12.903 14011 14222 D OpenGLRenderer: endAllActiveAnimators on 0xb40000726da53000 (RippleDrawable) with handle 0xb40000726d93d380
07-05 19:18:12.914 14011 14021 D BLASTBufferQueue: [VRI[SettingsActivity]#5](f:0,a:2) destructor()
07-05 19:18:12.914 14011 14021 D BufferQueueConsumer: [VRI[SettingsActivity]#5(BLAST Consumer)5](id:36bb00000005,api:0,p:-1,c:14011) disconnect
07-05 19:18:12.947 14011 14011 D IntegrationRepositoryImpl: isAppLocked(): false. (LockEnabled: false, appActive: true, expireMillis: 0, currentMillis: 1751735892946)
07-05 19:18:12.947 14011 14011 D IntegrationRepositoryImpl: setAppActive(): true
07-05 19:18:19.655 14011 14011 E mpanion.android: Invalid resource ID 0x00000000.
07-05 19:18:20.892 14011 14011 E mpanion.android: Invalid resource ID 0x00000000.
07-05 19:18:26.274 14011 14011 E mpanion.android: Invalid resource ID 0x00000000.
07-05 19:18:26.314 14011 14011 D VRI[SettingsActivity]: update {(0,0)(fillxfill) layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:18:26.314 14011 14011 D VRI[SettingsActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:18:26.314 14011 14011 D VRI[SettingsActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:18:26.314 14011 14011 D VRI[SettingsActivity]:   bhv=DEFAULT
07-05 19:18:26.314 14011 14011 D VRI[SettingsActivity]:   fitSides=} by setLayoutParams
07-05 19:18:27.844 14011 14011 E mpanion.android: Invalid resource ID 0x00000000.
07-05 19:18:27.880 14011 14011 D VRI[SettingsActivity]: update {(0,0)(fillxfill) layoutInDisplayCutoutMode=always ty=BASE_APPLICATION wanim=0x10302fe
07-05 19:18:27.880 14011 14011 D VRI[SettingsActivity]:   fl=LAYOUT_IN_SCREEN LAYOUT_INSET_DECOR SPLIT_TOUCH HARDWARE_ACCELERATED DRAWS_SYSTEM_BAR_BACKGROUNDS
07-05 19:18:27.880 14011 14011 D VRI[SettingsActivity]:   pfl=NO_MOVE_ANIMATION FORCE_DRAW_STATUS_BAR_BACKGROUND FIT_INSETS_CONTROLLED
07-05 19:18:27.880 14011 14011 D VRI[SettingsActivity]:   bhv=DEFAULT
07-05 19:18:27.880 14011 14011 D VRI[SettingsActivity]:   fitSides=} by setLayoutParams
07-05 19:18:27.880 14011 14210 D LogcatReader$readLog: Read logcat for pid 14011

```

**Comment by kzshantonu** [comment]
+1 

All tiles say "removed" and nothing new can be added either. App itself works fine.

version 2025.6.6-full
io.homeassistant.companion.android

**Comment by dthreee** [comment]
Seeing the same thing on the latest update (2025.6.6-full).
Also noticed that you can’t add any Android auto favorites, or tiles, or entities for shortcuts. Under “Manage device controls”, where it says choose the entities you want to control with the built in device controls, there are no entities listed, and it just says “no entities available.”

**Comment by dshokouhi** [comment]
Can you guys please share the logs you have as well after reproducing the issue?

We have added more logging since the last update.

**Comment by meldarionqeusse** [comment]
The logs I included are after the issue occurs. Is there some other place to get more logs?

**Comment by dthreee** [comment]
Log attached. The “critical failure” messages appear after attempting to use the device control buttons.

[homeassistant_companion_log_6-6-2025_17-39-11.txt](https://github.com/user-attachments/files/21092547/homeassistant_companion_log_6-6-2025_17-39-11.txt)

**Comment by kzshantonu** [comment]
Log: https://bin.mni.li/7ZUP2QYxaNKvbri1OPk35#-toCZlYPaPvnvxrc9wF3m-UCo_JJfZ3WRJxugSHH2sA

Access code: tree-funeral-wayfarer-experience

**Comment by TimoPtr** [comment]
This issue has been fixed but not included in the release unfortunately. It will in the next release. You can test the fix by joining the beta 

https://play.google.com/apps/testing/io.homeassistant.companion.android

**Comment by meldarionqeusse** [comment]
Whats the version number pls? I still see with 5.6.6 and I am subscribed to beta

**Comment by kzshantonu** [comment]
> Whats the version number pls? I still see with 5.6.6 and I am subscribed to beta

version 2025.7.1-full
io.homeassistant.companion.android

**Comment by meldarionqeusse** [comment]
Can confirm device controls are working with the latest version 2025.7.1. Thanks
