### ISSUE TITLE
Crashes when opening companion app settings

### ISSUE THREAD

**Issue by FliegenderPinguin** [home-assistant/android#5789]
**Home Assistant Android app version(s):** not sure but up to date as per play store 

**Android version(s):** 14

**Device model(s):** Samsung Galaxy A52

**Home Assistant version:** 2025.9.3

**Last working Home Assistant release (if known):**

**Description of problem, include YAML if issue is related to notifications:**

I am using the latest HA android app and wanted to turn on the locations to work on a new automation. Unfortunately, whenever I go to the settings and then click companion app, the next screen loads but immediately freezes and then the app crashes.
A phone restart doesnt solve the problem.
I am accessing as an admin.

Another phone (not admin) can access the app settings without problem.
HA runs wonderful and without issues otherwise.

**Companion App Logs:**

```

```

**Screenshot or video of problem:**

**Additional information:**

**Comment by nikos445** [comment]
Same Here...  2 different Tablets.
Update to 2025.09.03 (pre-release seems to solve the issue) - will test it further and report back if I see it again.

**Comment by TimoPtr** [comment]
It has been fixed in 2025.9.2 that is currently in beta and waiting for Google review. It was initially reported on this issue https://github.com/home-assistant/android/issues/5665

**Comment by danielducu** [comment]
Issue persists even on 2025.9.2 it seams to work for a while but revisiting settings a few times freezes the companion app settings section.

**Comment by TimoPtr** [comment]
> Issue persists even on 2025.9.3 it seams to work for a while but revisiting settings a few times freezes the companion app settings section.

From where did you install the application?

**Comment by danielducu** [comment]
> > Issue persists even on 2025.9.3 it seams to work for a while but revisiting settings a few times freezes the companion app settings section.
> 
> From where did you install the application?

Correction: 2025.9.2

**Comment by TimoPtr** [comment]
> > > Issue persists even on 2025.9.3 it seams to work for a while but revisiting settings a few times freezes the companion app settings section.
> > 
> > From where did you install the application?
> 
> Correction: 2025.9.2

Could you share the logs when the issue occurs?
