### ISSUE TITLE
App reloads everytime I open it. 

### ISSUE THREAD

**Issue by pizzapants** [home-assistant/android#590]
**Home Assistant Android version:**
1.9.0-167
**Android version:**
Android 10 One UI 2.1
**Phone model:**
Samsung S20
**Home Assistant version:**
 0.109.6
**Last working Home Assistant release (if known):**
Always done this. 
**Description of problem:**
Every time I launch the app, it will reload the front end as if the app was not stored in ram. For example, If I launch it it will reload. If I then go to the home screen (using Nova), then immediately launch it again it will reload again. 

If I quick switch to another app, then back to HASS it does _not_ do this. 

Locking the app in RAM (keep app open for quick launching) does not change this. 

I turned off battery optimization and it solved this issue for a few days, but it has now reverted back to this behavior. 

Strangely, if I launch the app from the Google Play store page, it also does not show this behavior. 

**Traceback (if applicable):**

```

```

**Screenshot of problem:**

**Additional information:**

**Comment by mattclar** [comment]
I get the same issue. Im not sure if this is a 'bug' or just how its implemented but this is very frustrating as I didnt get this if I had it as a progressive Web App. But obviously the various other benefits of the full app are great!
Im using a oneplus 6T

**Comment by tracestep** [comment]
I have the same issue on app version 2.0.0.235-full with HA 0.113.2, using Nova Launcher on Android 10 (Samsung S10e). Actually it was the first thing I noticed about the app after installing; using the "Add to home screen" feature of Chrome did not exhibit this behavior, but I suppose using it as a Chrome webapp will not give me notifications. 

It is strange indeed that opening the app from the Play Store does not show this behavior, I didn't know there could be a difference and I just confirmed it. Could that be a sign of some interaction of an app bug and a Nova Launcher bug? I have similar problems with some (probably badly written) apps, link my building alarm control app.

**Comment by tracestep** [comment]
Well, the next day I posted a response, the app got updated to 2.1.0.239-full and works correctly now. So the bug appears to have been fixed.

**Comment by dshokouhi** [comment]
I personally still see the app reloading every now and then, trying to pin it down by finding the logcat error.

**Comment by JBassett** [comment]
I'm not sure you'll find an error.  If the system decides to kill the app when you put it in the background then there isn't much we can do about it.

**Comment by dshokouhi** [comment]
I was afraid of that lol, wonder if we need a persistent notification to keep the app alive?

**Comment by tracestep** [comment]
There surely must be a way to keep an app alive or dormant in the background that doesn't require a complete reload (splash screen et al) when go to the homescreen for a single second. Yeah, I don't mind an ocasional refresh after I have not used the app for half an hour or so... but the behavior the OP described happened every single time, and the newest version seems to have fixed it at least for these short intervals.

**Comment by SteveDinn** [comment]
Can we keep the app on the same page when reloading because we have disconnected from the 'home' wifi? I feel like it should remember the URL that our was on. Currently, it always reloads back to the first tab on the first dashboard.

It would be a dream if it also remembered how far it was scrolled down the page.

**Comment by dshokouhi** [comment]
I think this issue is now fixed in the latest production release.  Can you guys check on 2.2.0?

**Comment by dshokouhi** [comment]
Well I may have spoken too soon.  On my own Pixel 4 XL this is behaving as desired when I follow the steps mentioned in the first post.  My wifes phone which is a Pixel 3 XL is having this issue and I thought the latest beta would've fix it but I guess the errors I saw earlier were unrelated to this.  So I ended up reproducing the issue and grabbing the logs for when it happened.

```
2020-08-16 14:22:58.623 1355-2142/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[76,1106][329,1399]} from uid 10152
2020-08-16 14:22:58.633 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{d22a8db token=Token{c684dea ActivityRecord{b3e31d5 u0 io.homeassistant.companion.android/.launch.LaunchActivity t23389}}}
2020-08-16 14:22:58.786 1355-3483/? I/ActivityTaskManager: START u0 {cmp=io.homeassistant.companion.android/.webview.WebViewActivity (has extras)} from uid 10270
2020-08-16 14:22:58.792 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{89926af token=Token{ddd8e8e ActivityRecord{f5b3e89 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}}
2020-08-16 14:22:59.101 1355-1443/? I/ActivityTaskManager: Displayed io.homeassistant.companion.android/.webview.WebViewActivity: +204ms
2020-08-16 14:22:59.125 30304-31495/? D/OkHttp: {"app_data": {}
2020-08-16 14:22:59.233 2478-4608/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=io.homeassistant.companion.android], packageName=io.homeassistant.companion.android]
2020-08-16 14:22:59.300 2478-4608/? I/GeofencerStateMachine: addGeofences called by io.homeassistant.companion.android
2020-08-16 14:22:59.305 30304-31499/? D/OkHttp: {}
2020-08-16 14:22:59.337 665-665/? E/Layer: [Surface(name=AppWindowToken{89926af token=Token{ddd8e8e ActivityRecord{f5b3e89 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}})/@0xe13dbf9 - animation-leash#0] No local sync point found
2020-08-16 14:22:59.337 665-665/? E/Layer: [Surface(name=AppWindowToken{89926af token=Token{ddd8e8e ActivityRecord{f5b3e89 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}})/@0xe13dbf9 - animation-leash#0] No local sync point found
2020-08-16 14:22:59.533 30304-30360/? D/StorageSensor: PATH /storage/emulated/0/Android/data/io.homeassistant.companion.android/files is mounted true and removable is false
2020-08-16 14:22:59.644 30304-30338/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=4062ac0a-5ab1-4502-be33-97f89f7e46d8, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
2020-08-16 14:23:18.675 1355-3444/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.homeassistant.companion.android/.launch.LaunchActivity bnds=[76,1106][329,1399]} from uid 10152
2020-08-16 14:23:18.681 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{a7a681b token=Token{1d6822a ActivityRecord{bef8f15 u0 io.homeassistant.companion.android/.launch.LaunchActivity t23389}}}
2020-08-16 14:23:18.721 1355-4404/? I/ActivityTaskManager: START u0 {cmp=io.homeassistant.companion.android/.webview.WebViewActivity (has extras)} from uid 10270
2020-08-16 14:23:18.726 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{3098bd0 token=Token{be3bf93 ActivityRecord{9692c82 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}}
2020-08-16 14:23:18.804 30304-31520/? D/OkHttp: {"app_data": {}
2020-08-16 14:23:18.830 1355-1443/? I/ActivityTaskManager: Displayed io.homeassistant.companion.android/.webview.WebViewActivity: +64ms
2020-08-16 14:23:18.832 2478-4608/? I/GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=io.homeassistant.companion.android], packageName=io.homeassistant.companion.android]
2020-08-16 14:23:18.913 30304-31525/? D/OkHttp: {}
2020-08-16 14:23:18.976 2478-5938/? I/GeofencerStateMachine: addGeofences called by io.homeassistant.companion.android
2020-08-16 14:23:19.063 30304-30360/? D/StorageSensor: PATH /storage/emulated/0/Android/data/io.homeassistant.companion.android/files is mounted true and removable is false
2020-08-16 14:23:19.072 665-665/? E/Layer: [Surface(name=AppWindowToken{3098bd0 token=Token{be3bf93 ActivityRecord{9692c82 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}})/@0x39c023d - animation-leash#0] No local sync point found
2020-08-16 14:23:19.072 665-665/? E/Layer: [Surface(name=AppWindowToken{3098bd0 token=Token{be3bf93 ActivityRecord{9692c82 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}})/@0x39c023d - animation-leash#0] No local sync point found
2020-08-16 14:23:19.243 30304-30338/? I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=b940bc23-61c2-419a-937a-93ff66288e7e, tags={ io.homeassistant.companion.android.sensors.SensorWorker } ]
```

What sticks out to me here are the following statements

```
2020-08-16 14:23:19.072 665-665/? E/Layer: [Surface(name=AppWindowToken{3098bd0 token=Token{be3bf93 ActivityRecord{9692c82 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}})/@0x39c023d - animation-leash#0] No local sync point found
```

and

```
2020-08-16 14:23:18.681 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{a7a681b token=Token{1d6822a ActivityRecord{bef8f15 u0 io.homeassistant.companion.android/.launch.LaunchActivity t23389}}}
2020-08-16 14:23:18.726 1355-1439/? W/WindowManager: TaskSnapshotSurface.create: Failed to find main window for token=AppWindowToken{3098bd0 token=Token{be3bf93 ActivityRecord{9692c82 u0 io.homeassistant.companion.android/.webview.WebViewActivity t23389}}}
```

I wonder why this happens when we open the app from the launcher as opposed to recent apps only on certain devices.

**Comment by dshokouhi** [comment]
Can you guys confirm if you restart your device and try the steps again if the issue is no longer reproducible? After my comment last night where I mentioned my Pixel 4 XL was not having this issue it suddenly appeared (seemingly after an app update). I then restarted my device and I did not see the issue again.  I suspect it will show up again in a few days

**Comment by dshokouhi** [comment]
Today we had another beta release, before I updated to the latest version the app was not reloading when I opened.  As soon as I updated to the latest version this issue came back, then again I restarted my phone and the app no longer works.  So the question is why does this only get triggered when we update the app?  And why does a restart correct it?

**Comment by SilverWx** [comment]
Even with app pinned in multitask I got this behavior on my s10

**Comment by Mincka** [comment]
I am on beta 406 and also see this behavior each time the application is killed.
Adding on the fact that it adds a slight delay, some components might not load properly on first loading (https://github.com/kalkih/mini-media-player/issues/426). I'm not saying this is caused by the Android app, just that's a side effect.

**Comment by Mincka** [comment]
I found a "workaround" to prevent the reloading of the interface.
In the App switcher, I set the app as "Keep open for quick launching" and it does the job.

**Comment by dshokouhi** [comment]
@Mincka that sounds more like a device specific setting.

If the app is crashing then that it may also seem to be "killed" but that is a separate case from this issue.  I am not sure if even adding a persistent notification will solve this issue.  Even Tasker from time to time may have their UI killed while services run in the background, even with their persistent notification.

I think the main thing here is that if the app services are still running (i.e. sensors and location still update) then this issue should be good to close.  All apps reload, even chrome tabs and more so we are a webview so it may also be reloading the tab much like chrome does. This may appear as if the app was closed when in fact the webview was just reloading.  The telltale sign the app is still running to some extent is our services.

**Comment by SilverWx** [comment]
The problem is gone for ;)

**Comment by dshokouhi** [comment]
Closing as not much we can do if the android system deems the app needs to be stopped. If there is a crash then we should fix those but no error logs have been reported.

**Comment by sebaschn** [comment]
User from the future 2025.
This problem still exists for me...

**Comment by LegionSMOKEZ** [comment]
> User from the future 2025. This problem still exists for me...

Same here - Anyone ever find a fix? I have my app and HA set for constant connection, etc... simple switching apps for a second completely makes the companion app reload. (Sometimes it won't even show in the wheel of open apps)
