### ISSUE TITLE
Status bar has light text on lightbackground with light theme

### ISSUE THREAD

**Issue by gadgetchnnel** [home-assistant/android#715]
**Home Assistant Android version:**
2.1.0-4-ge42d4c2-243-full

**Android version:**
10 (EMUI 10.1.0)

**Phone model:**
Huawei Mate 20 Pro

**Home Assistant version:**
0.114.0b2

**Last working Home Assistant release (if known):**

**Description of problem:**
When using a light theme, in this case [Google Light Theme](https://github.com/JuanMTech/google_light_theme), the status bar will show light text on a light background (in this case white on light grey) making it difficult or impossible to read. This didn't appear to have been an issue before [this PR](https://github.com/home-assistant/android/pull/714) was merged, but that may simply have been due to this particular theme using a rgb colour rather than a hex colour and so it was previously using the default colour for the status bar.

**Traceback (if applicable):**

```

```

**Screenshot of problem:**
![image](https://user-images.githubusercontent.com/2099542/89716390-750ef580-d9a4-11ea-8c27-f1f3c40d654c.png)

**Additional information:**

**Comment by dshokouhi** [comment]
@gadgetchnnel can you try the debug APK from: https://github.com/home-assistant/android/actions/runs/200575777

The fix for dark mode detection may or may not correct this case, we are just curious

**Comment by dshokouhi** [comment]
Just tested the theme locally with my build, looks like it should fix this.  This is with my device theme on dark.

![image](https://user-images.githubusercontent.com/1634145/89716814-15ddc080-d965-11ea-947e-ca66a0ae7568.png)

**Comment by dshokouhi** [comment]
Also I think this is a duplicate of #443 ?

**Comment by gadgetchnnel** [comment]
That build fixes the automatic switching between the Light and Dark theme, but the status bar text is still a problem when using a light theme.

I assume you actually mean #433 ( #443 seems to be a PR relating to service widgets). Yes, this does look like a duplicate of that issue. I hadn't noticed that one and, since this only appeared recently when the fix for themes using rgb colours was merged I'd assumed it was a new issue.

The issue here seems to be that the status bar always uses white text, even if the theme colour is light.

Going from [this StackOverflow answer](https://stackoverflow.com/a/38383439) the solution is to set **windowLightStatusBar** to true if the status bar colour is light (and to false if it is dark) which will tell Android to use a text colour which will show up over the status bar.

**Comment by dshokouhi** [comment]
Thanks for confirming and for the SO link @gadgetchnnel going to close this now and we can pick things back up in #433. May need some time to see whats going on.  My debug builds aren't loading the status bar properly so need to troubleshoot that.
